---
title: "class1_1"
author: "Weronika Klecel"
date: "2024-10-08"
output: html_document
---

# Zadanie 1: poznajemy RStudio

1.  Uruchom RStudio na swoim komputerze

2.  Zapoznaj się z interfejsem użytkownika

3.  Stwórz nowy skrypt R

4.  W skrypcie napisz komentarze opisujące funkcje poszczególnych paneli

5.  Znajdź w RStudio ustawienia i zmień motyw kolorystyczny

6.  Napisz w komentarzu, jaki motyw wybrałeś/aś i dlaczego

7.  Zapisz skrypt jako zadanie1.R w swoim folderze

8.  Prześlij plik do swojego repozytorium na GitHub

# Zadanie 2: tworzenie nowego skryptu

1.  Stwórz nowy skrypt R o nazwie zadanie2.R w RStudio

2.  Przećwicz przypisywanie wartości do zmiennych za pomocą operatorów `<-` oraz `=`

3.  Znajdź odpowiedź na zagadkę dotyczącą różnic między operatorami `<-` oraz `=`

4.  Przećwicz wydzielanie podzbioru z wektora

5.  Stwórz własny wektor zawierający liczby od 10 do 20

6.  Wydziel podzbiór zawierający tylko liczby parzyste

Zapisz skrypt i prześlij go do swojego repozytorium na GitHub

# Zadanie 3: wektory, macierze, ramki danych

1.  Stwórz wektor liczb całkowitych

2.  Utwórz macierz z danych liczbowych

3.  Stwórz ramkę danych zawierającą różne typy danych

4.  Zdefiniuj listę zawierającą wektor, macierz i ramkę danych

5.  Stwórz własną ramkę danych zawierającą Twoje dane oraz dane dwóch Twoich znajomych

6.  Upewnij się, że kolumna `ulubiony_kolor` jest typu `factor`

7.  Wyświetl strukturę swojej ramki danych za pomocą funkcji `str()`

8.  Zapisz skrypt jako zadanie3.R i prześlij go do swojego repozytorium

# Zadanie 4: operacje arytmetyczne i logiczne

1.  Wykonaj operacje arytmetyczne na zmiennych:

    `x <- 15`

    `y <- 4`

2.  Użyj operatorów relacyjnych do porównania wartości

3.  Stwórz wyrażenia logiczne i sprawdź ich wyniki

4.  Wybierz dwie liczby, np. dzień i miesiąc urodzenia

5.  Przeprowadź na nich operacje arytmetyczne i logiczne

6.  Napisz komentarze opisujące, co robisz w każdym kroku

7.  Zapisz skrypt jako zadanie4.R i prześlij go do swojego repozytorium

# Zadanie 5: funkcje statystyczne i logiczne

1.  Użyj funkcji statystycznych na wektorze danych

2.  Wykorzystaj funkcje do tworzenia sekwencji i powielania elementów

3.  Sortuj i porządkuj dane

4.  Użyj funkcji `ifelse()` do stworzenia nowej zmiennej

5.  Stwórz wektor zawierający liczby od 1 do 100

6.  Użyj funkcji `ifelse()` do określenia podzielności liczb przez 3, 5, lub oba

7.  Wyświetl wynik w konsoli

8.  Zapisz skrypt jako zadanie5.R i prześlij go do swojego repozytorium

# Zadanie 6: instalacja pakietu

1.  Zainstaluj pakiet `ggplot2`

2.  Załaduj pakiet

3.  Sprawdź dokumentację pakietu

4.  Zainstaluj i załaduj dodatkowy pakiet, który Cię zainteresuje

5.  Napisz krótki opis w komentarzu

6.  Zapisz skrypt jako zadanie6.R i prześlij go do swojego repozytorium

# Zadanie 7: podstawowa wizualizacja danych

1.  Załaduj pakiet `ggplot2`

2.  Wykorzystaj zbiór danych `mtcars`

3.  Stwórz wykres punktowy przedstawiający zależność między mocą (`hp`) a zużyciem paliwa (`mpg`)

4.  Stwórz wykres słupkowy przedstawiający liczbę samochodów dla każdej liczby cylindrów (`cyl`)

5.  Dodaj kolory do słupków i odpowiednie opisy osi i tytuł

6.  Zapisz skrypt jako zadanie7.R i prześlij go do swojego repozytorium

# Zadanie 8: operacja na zbiorach danych

1.  Załaduj pakiet `dplyr`

2.  Wykorzystaj zbiór danych `mtcars`

3.  Wykonaj następujące operacje: filtrowanie, wybieranie kolumn, tworzenie nowej zmiennej, grupowanie i podsumowanie

4.  Wyświetl wyniki każdej operacji

5.  Zapisz skrypt jako zadanie8.R i prześlij go do swojego repozytorium

# Zadanie 9: tworzenie pliku .Rmd

1.  W RStudio stwórz nowy plik RMarkdown

2.  Napisz krótki raport podsumowujący wyniki z zadań 7 i 8

3.  Dodaj sekcję z własną analizą danych

4.  Użyj funkcji `kable()` z pakietu `knitr` do sformatowania tabel

5.  Wygeneruj raport w formacie HTML

6.  Zapisz plik jako zadanie9.Rmd i prześlij go do swojego repozytorium

# Zadanie 10: wczytywanie pliku Excel

1.  Zainstaluj i załaduj pakiet `readxl`

2.  Wczytaj dane z pliku `dane_zad10.xlsx`

3.  Sprawdź strukturę danych i wyświetl pierwsze wiersze

4.  Wykonaj prostą analizę, np. oblicz średnią wybranej zmiennej

5.  Stwórz wykres przedstawiający zależność między dwoma zmiennymi

6.  Dodaj odpowiednie opisy osi i tytuł wykresu

7.  Zapisz skrypt jako zadanie10.R i prześlij go do swojego repozytorium

# Zadanie 11: tworzenie interaktywnych wykresów

1.  Zainstaluj i załaduj pakiet `plotly`

2.  Stwórz interaktywny wykres na podstawie danych z zadania 7

3.  Eksploruj możliwości interaktywne wykresu

4.  Stwórz interaktywny wykres wykorzystując własne dane

5.  Dodaj interaktywne etykiety za pomocą argumentu `text`

6.  Zapisz skrypt jako zadanie11.R i prześlij go do swojego repozytorium

# Zadanie 12: : tworzenie interaktywnych aplikacji

1.  Zainstaluj i załaduj pakiet `shiny`

2.  Stwórz prostą aplikację, która pozwala użytkownikowi wybrać liczbę podziałek histogramu

3.  Rozbuduj aplikację, dodając możliwość wyboru zmiennej i koloru histogramu

4.  Zapisz skrypt jako zadanie12.R i prześlij go do swojego repozytorium

# Zadanie 13: tworzenie grafik z pakietem esquisse

Zainstaluj i załaduj pakiet `esquisse`

1.  Uruchom interfejs graficzny

2.  Stwórz wykres korzystając z interfejsu przeciągnij i upuść

3.  Wyeksportuj wygenerowany kod ggplot2 i wklej go do skryptu

4.  Użyj własnych danych do stworzenia wykresu

5.  Zapisz skrypt jako zadanie13.R i prześlij go do swojego repozytorium

# Zadanie 14: notatki z zadań

1.  Utwórz plik README.md w folderze `1-IntroToR` w swoim repozytorium

2.  Opisz krótko każde zadanie

3.  Dodaj instrukcje dotyczące instalacji wymaganych pakietów

4.  Dodaj sekcję z wnioskami i refleksjami na temat nauki R

5.  Podziel się napotkanymi trudnościami i sposobami ich rozwiązania

6.  Prześlij plik do swojego repozytorium
